---
- name: Update CentOS and Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Update Ubuntu
      apt:
        upgrade: dist
      when: ansible_os_family == 'Debian'

