---
- name: Create directory
  hosts: server
  become: yes

  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: /jeetu-rocks
        state: directory

    - name: Create file
      ansible.builtin.file:
        path: /jeetu-rocks/myfile.txt
        state: touch
        mode: "0660"
        owner: jeetu
        group: jeetu        
